# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ae32fd1e7982e14a74ee48b88aae7669f502ee46451564900cc046afa55f5681c21b5182e18f963debf784be335347e035bedbe7df33bbd90182a13fad6614

test:
  secret_key_base: 1d88aa02578ca3ecc6d203f793d658934f9605069c39f0b8e4911d5b6eaf3a4323aeccd652983840444a59a34c915a4cacf5eba7807be87aa9e28b3d4ce13106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
